### ISSUE TITLE
pressing back button twice on dark mode selection screen exits

### ISSUE THREAD

**Issue by om26er** [xconnio/wick-ui#56]
1. open app in browser
2. go to settings
3. go to Select theme
4. press back button twice

What happens: app exits

What should happen: main screen should show. The app should exit on third back press

**Comment by shakeebkhan66** [comment]
@om26er 
I removed the setting part in the web version to change the theme and make it this way. @Mahad-10 showed me one similar example.
https://github.com/xconnio/wick-ui/assets/73787635/7e5cc51e-b56e-4740-8ad2-e8d9070ec86c
